#!/usr/bin/env python3
"""Generate the built-in exercise i18n artifacts from the seed asset + names-de.json.

Outputs (all overwritten in place):
- the exercise_* <string> block in app/src/main/res/values/strings.xml (EN = seed names)
- the exercise_* <string> block in app/src/main/res/values-de/strings.xml (from names-de.json)
- app/src/main/kotlin/de/simiil/liftlog/ui/exercises/BuiltInExerciseNames.kt (UUID -> R.string)

Idempotent; re-run after any seed or translation change. Never edit the outputs by hand.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
NAMES_DE = os.path.join(HERE, "names-de.json")
EN_XML = os.path.join(ROOT, "app/src/main/res/values/strings.xml")
DE_XML = os.path.join(ROOT, "app/src/main/res/values-de/strings.xml")
KT = os.path.join(ROOT, "app/src/main/kotlin/de/simiil/liftlog/ui/exercises/BuiltInExerciseNames.kt")


def find_seed():
    d = os.path.join(ROOT, "app/src/main/assets/seed")
    files = sorted(f for f in os.listdir(d) if re.fullmatch(r"exercises\.v\d+\.json", f))
    assert len(files) == 1, f"expected exactly one seed asset, found {files}"
    return os.path.join(d, files[0])


def slug(n):
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]", "_", n.lower())).strip("_")


def xml_value(v):
    assert not re.search(r'[&<>"]', v), f"unsupported XML character in {v!r}"
    return v.replace("'", "\\'")


def replace_block(path, new_lines):
    text = open(path, encoding="utf-8").read()
    pat = re.compile(r'[ \t]*<string name="exercise_[a-z0-9_]+">.*</string>\n')
    ms = list(pat.finditer(text))
    assert ms, f"no exercise_* strings found in {path}"
    start, end = ms[0].start(), ms[-1].end()
    inner = text[start:end]
    assert inner.count("\n") == len(ms), f"exercise_* block not contiguous in {path}"
    open(path, "w", encoding="utf-8").write(text[:start] + "".join(new_lines) + text[end:])


seed_path = find_seed()
seed = json.load(open(seed_path, encoding="utf-8"))["exercises"]
de_names = json.load(open(NAMES_DE, encoding="utf-8"))

missing_de = [e["name"] for e in seed if e["name"] not in de_names]
assert not missing_de, f"names-de.json missing {len(missing_de)} names: {missing_de[:5]}..."
slugs = ["exercise_" + slug(e["name"]) for e in seed]
assert len(set(slugs)) == len(slugs), "slug collision"

en_lines = [f'    <string name="{s}">{xml_value(e["name"])}</string>\n' for s, e in zip(slugs, seed)]
de_lines = [f'    <string name="{s}">{xml_value(de_names[e["name"]])}</string>\n' for s, e in zip(slugs, seed)]
replace_block(EN_XML, en_lines)
replace_block(DE_XML, de_lines)

kt = [
    "package de.simiil.liftlog.ui.exercises\n",
    "\n",
    "import de.simiil.liftlog.R\n",
    "\n",
    "/**\n",
    " * Stable built-in exercise UUID -> display-name string resource (08-i18n-spec §3.1).\n",
    f" * GENERATED by tools/seed/gen_i18n.py from {os.path.basename(seed_path)} — do not edit by hand;\n",
    " * BuiltInExerciseNamesTest locks it in sync. Membership here IS the built-in test —\n",
    " * custom exercises (random UUIDs) are absent.\n",
    " */\n",
    "object BuiltInExerciseNames {\n",
    "    val resById: Map<String, Int> =\n",
    "        mapOf(\n",
]
kt += [f'            "{e["id"]}" to R.string.{s},\n' for s, e in zip(slugs, seed)]
kt += ["        )\n", "}\n"]
open(KT, "w", encoding="utf-8").write("".join(kt))

print(f"generated from {os.path.basename(seed_path)}: {len(seed)} entries -> EN block, DE block, BuiltInExerciseNames.kt")
